### ISSUE TITLE
not blurring faces

### ISSUE THREAD

**Issue by joshinils** [tfaehse/DashcamCleaner#11]
i screen recorded a clip starting from https://youtu.be/EfdmAuB7JzU?t=296 and cut it down to one second.
i have an amd gpu, so cuda does not work for me, cpu time for that one second clip was 3minutes 8sec.

none of the faces are blurred in the output clip.
i used the 1080p_medium_rect weights 
and inference_size 1080
roi_multi of 1
quality of 10
threshold of 1
blur_size of 10
frame_memory of 1

**Comment by tfaehse** [comment]
That's regrettable. I've just tested this, for now just a few notes:
- my input data is fairly bad, since it's just my dashcam footage. Faces are rare, especially high-def profile shots like these. This will hopefully get better, especially also because of a really nice data donation I received. 
- The `_rect` weights files don't perform well. I originally thought the higher resolution of training fixed-size images would benefit detection (especially of small objects, i.e. farther away plates), but Yolov5's mosaic data loader makes such a massive (positive) difference that it absolutely isn't the case.
For now, using `_mosaic` weights should yield better results. Long-term I'll hopefully be able to publish much better trained networks. I'll have a look at your PR and the other issue soon (I promise!), I'm unfortunately fairly busy at the moment.

**Comment by joshinils** [comment]
hm, so you're saying I need different weights from somewhere?

I just did another test, footage from my bicycle driving past parked cars.
none of the (german) licence plates are blurred for any of the 8 weights files /(1080p|720p)_(small|medium)_(mosaic|rect).pt/

**Comment by tfaehse** [comment]
Could you send me a snippet of such a recording? I'm not saying results should be perfect, but I've tried lots of different input data by now and nothing at all sounds strange.
If you don't want to post such videos publicly feel free to message me privately, you can reach me at my git user at me or gmail dot com. I'll have a look!

**Comment by joshinils** [comment]
problem was my python packages and maybe using a threshold of 1
