### ISSUE TITLE
Question Linux support + FFMPEG_BINARY

### ISSUE THREAD

**Issue by teminvictus** [tfaehse/DashcamCleaner#4]
hi,
thanks for your work. not an issue but 2 questions.

The Ui only works in Windows I guess?
Or should it work in Linux too?

Can you point out how to set the ffmpeg environment variable in windows?

**Comment by tfaehse** [comment]
Hi @teminvictus, thank you for your interest! 

PySide2 should work on most platforms, I've just verified it on my Ubuntu machine and the tool also works fine, with a few... unforeseen issues, since I'd only tested it on Windows before. Bottom line though, blurring works (with CUDA acceleration too)!

- Cancelling a job seems to crash the GUI for now, I'll have to look into it. Spawning processes should be much more straightforward on Linux, some of the workarounds for Windows probably break it
- GUI test isn't rendered as nicely as on Windows, at least not on higher DPI screens

Oracles [guide for environment variables](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html) is pretty nice. At the end, just add a new one with the name "FFMPEG_BINARY" and the path to your executable as the value.
