### ISSUE TITLE
How to use GPU on Desktop Version?

### ISSUE THREAD

**Issue by nils8107** [tfaehse/DashcamCleaner#77]
Hello I use the GUI.
When i render a Video it only uses my CPU (i713700k)
My RTX4090 is idle. How can I use the GPU?

Thank you

**Comment by Dave04O4** [comment]
Da würde ich mich mit anschließen.

Ich habe es mit den älteren Versionen immer hingekriegt, aber jetzt nicht mehr.

**Comment by Maxolus** [comment]
Hey, had the same problem today. For me, the requirements.txt file installed a pytorch version without GPU support.

Solution that worked for me:

1. uninstall torch, torchaudio and torchvision with pip.
2. generate pip command for your settings (conda version can be found with nvidia-smi command) on pytorch dot org with correct settings and run in the conda environment.

Cheers

**Comment by fragy007** [comment]
> Hello Maxolus
> 
> Thank your for your solution. As I understand:
> 
> Part 1: pip uninstall torch pip uninstall torchaudio pip uninstall torchvision
> 
> Part 2: When i run "nvidia-smi command" i get this: NVIDIA-SMI 536.67 Driver Version: 536.67 CUDA Version: 12.2
> 
> On pytorch dot org I only have those Options: CUDA 11.7 or CUDA11.8
> 
> I installed now: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> Now CPU is 12% and GPU is with Spikes also busy now. But far from high usage... Is that normal? But its faster now than before with 100%CPU.
> 
> And Please someone explain:
> 
> -Feather edges (Set to 1) -Batch Size (Set to 16) -Blur Workers (Now is set to 1) what this Value do?
> 
> ![pytorch](https://user-images.githubusercontent.com/140107280/259112880-c82d3c95-1c2d-49df-a87a-abbfa57a6e35.png)
> 
> Any advice please. Thank you

Thanks a lot!
These steps where helpful! RTX3090 is now running fine instead CPU only :)

**Comment by tfaehse** [comment]
Happy to see that things worked out!

> -Feather edges (Set to 1)
-Batch Size (Set to 16)
-Blur Workers (Now is set to 1) what this Value do?

Just for the record, since it's fairly important: the tool does a three stage process for the video, in "batches":
1. Read x frames (batch size)
2. Pass x frames into the detector (batch size)
3. Blur x frames (in y == blur workers processes)
4. Write x frames

Effectively, you want the batch size to be as large as possible, before saturating your VRAM. Blur workers should be the same or smaller, depending on how much normal RAM you have available.
Interestingly enough, the detector (with GPU support) is often not even the slowest part of this chain, but the blurring/writing is. In the future, I'll try to split these steps up a bit (detect first, then blur, fully sequentially). This will also allow me to run tracking of boxes etc.
